name: Create Release

on:
  push:
    branches:
      - release
permissions: write-all

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile executable
        run: |
          cd ${{ github.workspace }}
          pip install pyinstaller
          pip install PySimpleGUI
          pip install pillow
          pyinstaller --onefile --icon=favicon.ico main.pyw --name=PixelPlay
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.1.0
          release_name: Release v1.1.0
          body: |
            What's new?
            🎉 Transform your images into a picture-perfect masterpiece!
            🖼️ PixelPlay now supports seamless conversion to JPG, BMP, and TIFF formats, making it easier than ever to share your stunning visuals with the world.
            Say goodbye to compatibility issues and hello to versatility with just a few clicks!

            What's new?

            Added BMP, TIFF conversions
            Fixed type conversion with PNG and JPG
          draft: false
          prerelease: false
      - name: Upload Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/PixelPlay.exe
          asset_name: PixelPlay.exe
          asset_content_type: application/octet-stream
